from pathlib import Path
import zipfile, json, hashlib
root=Path(__file__).resolve().parents[1]
packages=[]
def package(name,files):
    target=root/name
    with zipfile.ZipFile(target,'w',zipfile.ZIP_DEFLATED,compresslevel=6) as z:
        for p,rel in files:z.write(p,rel)
    packages.append({'file':name,'bytes':target.stat().st_size,'sha256':hashlib.sha256(target.read_bytes()).hexdigest()})

# Precompressed responses can be regenerated by hosts; omitting them avoids
# shipping identical bytes twice in the deployment download.
package('RAINROT_Web_Deploy.zip',[(p,p.relative_to(root/'site')) for p in (root/'site').rglob('*') if p.is_file() and p.suffix!='.gz'])
files=[]
for folder in ['project','site','tools','reports']:
    for p in (root/folder).rglob('*'):
        rel=p.relative_to(root)
        if not p.is_file() or '.godot' in rel.parts or p.suffix in ['.gz','.log','.pid'] or '__pycache__' in rel.parts:continue
        if 'captures' in rel.parts or 'logs' in rel.parts or p.name in ['packages.json','delivery_checks.json']:continue
        files.append((p,rel))
for p in root.iterdir():
    if p.is_file() and (p.suffix in ['.ps1','.cmd','.md'] or p.name=='.gdignore'):files.append((p,p.name))
for name in ['web_nothreads_debug.zip','web_nothreads_release.zip','SOURCE.json']:
    p=root/'toolchain'/name;files.append((p,p.relative_to(root)))
package('RAINROT_Web_Project.zip',files)
(root/'reports/packages.json').write_text(json.dumps(packages,indent=2),encoding='utf-8')
print(json.dumps(packages,indent=2))
